another trial of RCMDCHECK wf

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -41,12 +41,20 @@ jobs:
       - uses: actions/checkout@v3 #
 
       - uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: ${{ matrix.config.r }}
-          http-user-agent: ${{ matrix.config.http-user-agent }}
-          use-public-rspm: true
+        # with:
+        #   r-version: ${{ matrix.config.r }}
+        #   http-user-agent: ${{ matrix.config.http-user-agent }}
+        #   use-public-rspm: true
 
       - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: any::rcmdcheck
+          needs: check
+      - uses: r-lib/actions/check-r-package@v2
+        with:
+          args: 'c("--no-manual", "--as-cran")'
+          error-on: '"error"'
+          check-dir: '"check"'
 
       # - uses: r-lib/actions/setup-pandoc@v2
       #
@@ -94,21 +102,21 @@ jobs:
       #     pkgs <- installed.packages()[, "Package"]
       #     sessioninfo::session_info(pkgs, include_base = TRUE)
       #   shell: Rscript {0}
-
-      - name: Check
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
-
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+#
+#       - name: Check
+#         env:
+#           _R_CHECK_CRAN_INCOMING_: false
+#         run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+#         shell: Rscript {0}
+#
+#       - name: Show testthat output
+#         if: always()
+#         run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+#         shell: bash
+#
+#       - name: Upload check results
+#         if: failure()
+#         uses: actions/upload-artifact@main
+#         with:
+#           name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+#           path: check
